name: jax-fem
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5=7_kmp_llvm
  - _x86_64-microarch-level=4=3_icelake
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py310h31b6992_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alsa-lib=1.2.15.3=hb03c661_0
  - async-timeout=5.0.1=pyhcf101f3_2
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyhcf101f3_1
  - backports.zstd=1.3.0=py310h69bd2ac_0
  - binutils_impl_linux-64=2.45.1=default_hfdba357_101
  - binutils_linux-64=2.45.1=default_h4852527_101
  - blosc=1.21.6=he440d0b_1
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=hda65f42_9
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=he90730b_1
  - certifi=2026.1.4=pyhd8ed1ab_0
  - cftime=1.6.5=py310hf779ad0_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cli11=2.6.0=h54a6638_0
  - conda-gcc-specs=14.3.0=he8ccf15_18
  - contourpy=1.3.2=py310h3788b33_0
  - cpython=3.10.19=py310hd8ed1ab_3
  - cycler=0.12.1=pyhcf101f3_2
  - cyclopts=4.5.4=pyhcf101f3_0
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.16.2=h24cb091_1
  - docstring_parser=0.17.0=pyhd8ed1ab_0
  - docutils=0.22.4=pyhd8ed1ab_0
  - double-conversion=3.4.0=hecca717_0
  - eigen=3.4.0=h54a6638_1
  - fenics=2019.1.0=hce2d2e0_59
  - fenics-dijitso=2019.1.0=pyhd8ed1ab_39
  - fenics-dolfin=2019.1.0=py310h04e48bf_59
  - fenics-ffc=2019.1.0=pyhd8ed1ab_40
  - fenics-fiat=2019.1.0=pyhd8ed1ab_40
  - fenics-libdolfin=2019.1.0=h53012b5_59
  - fenics-ufl=2019.1.0=py310hff52083_38
  - fftw=3.3.10=mpi_openmpi_h76e6d66_12
  - fmt=12.1.0=hff5e90c_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.17.1=h27c8c51_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py310h3406613_0
  - freetype=2.14.1=ha770c72_0
  - frozenlist=1.7.0=py310h9548a50_0
  - gcc=14.3.0=h0dff253_18
  - gcc_impl_linux-64=14.3.0=hbdf3cc3_18
  - gcc_linux-64=14.3.0=h298d278_21
  - gl2ps=1.4.2=hae5d5c5_1
  - glew=2.2.0=h3abd4de_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310h63ebcad_2
  - graphite2=1.3.14=hecca717_2
  - gxx=14.3.0=h76987e4_18
  - gxx_impl_linux-64=14.3.0=h2185e75_18
  - gxx_linux-64=14.3.0=h033eb0a_21
  - h2=4.3.0=pyhcf101f3_0
  - h5py=3.15.1=nompi_py310h4aa865e_101
  - harfbuzz=12.3.2=h6083320_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=mpi_openmpi_h8367ee7_6
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - hypre=2.32.0=mpi_openmpi_h398ea61_1
  - icu=78.2=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - jsoncpp=1.9.6=hf42df4d_1
  - kernel-headers_linux-64=6.12.0=he073ed8_5
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310haaf941d_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.45.1=default_hbd61a6d_101
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.5=h088129d_0
  - libamd=3.3.3=haaf9dc3_7100102
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libboost=1.88.0=hd24cca6_7
  - libboost-headers=1.88.0=ha770c72_7
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libbtf=2.3.2=h32481e8_7100102
  - libcamd=3.3.3=h32481e8_7100102
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_h0358290_openblas
  - libccolamd=3.3.4=h32481e8_7100102
  - libcholmod=5.3.1=h59ddab4_7100102
  - libclang-cpp21.1=21.1.8=default_h99862b1_3
  - libclang13=21.1.8=default_h746c552_3
  - libcolamd=3.3.4=h32481e8_7100102
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.18.0=h4e3cde8_0
  - libcxsparse=4.4.1=h32481e8_7100102
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.4=hecca717_0
  - libfabric=2.4.0=ha770c72_1
  - libfabric1=2.4.0=h8f87c3e_1
  - libffi=3.5.2=h3435931_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_18
  - libgcc-devel_linux-64=14.3.0=hf649bbc_118
  - libgcc-ng=15.2.0=h69a702a_18
  - libgfortran=15.2.0=h69a702a_18
  - libgfortran5=15.2.0=h68bc16d_18
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.4=h6548e54_1
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_18
  - libhwloc=2.12.1=default_hafda6a7_1003
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libklu=2.3.5=hf24d653_7100102
  - liblapack=3.11.0=5_h47877c9_openblas
  - libldl=3.3.2=h32481e8_7100102
  - libllvm20=20.1.8=hf7376ad_1
  - libllvm21=21.1.8=hf7376ad_0
  - liblzma=5.8.2=hb03c661_0
  - libnetcdf=4.9.3=nompi_hbf2fc22_104
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=openmp_hd680484_4
  - libopengl=1.7.0=ha4b6fd6_2
  - libparu=1.0.0=h17147ab_7100102
  - libpciaccess=0.18=hb9d3cd8_0
  - libpmix=5.0.8=h4bd6b51_2
  - libpng=1.6.55=h421ea60_0
  - libpq=18.2=hb80d175_0
  - libptscotch=7.0.6=h7e1c861_1
  - librbio=4.3.4=h32481e8_7100102
  - libsanitizer=14.3.0=h8f1669f_18
  - libscotch=7.0.6=hd4c538f_1
  - libspex=3.2.3=had10066_7100102
  - libspqr=4.3.4=h852d39f_7100102
  - libsqlite=3.51.2=hf4e2dac_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_18
  - libstdcxx-devel_linux-64=14.3.0=h9f08a49_118
  - libstdcxx-ng=15.2.0=hdf11a46_18
  - libsuitesparseconfig=7.10.1=h92d6892_7100102
  - libsystemd0=259.1=h6569c3e_0
  - libtheora=1.1.1=h4ab18f5_1006
  - libtiff=4.7.1=h9d88235_1
  - libudev1=259.1=h6569c3e_0
  - libumfpack=6.3.5=heb53515_7100102
  - libuuid=2.41.3=h5347b49_0
  - libvorbis=1.3.7=h54a6638_2
  - libvulkan-loader=1.4.341.0=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libxslt=1.1.43=h711ed8c_1
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=21.1.8=h4922eb0_0
  - loguru=0.7.3=pyh707e725_0
  - lz4-c=1.10.0=h5888daf_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - matplotlib=3.10.3=py310hff52083_0
  - matplotlib-base=3.10.3=py310h68603db_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mesalib=25.0.5=h57bcd07_2
  - meshio=5.3.5=pyhd8ed1ab_0
  - metis=5.1.0=hd0bcaf9_1007
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpi=1.0.1=openmpi
  - mpi4py=4.1.1=py310h42af892_103
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.2=py310h03d9f68_1
  - multidict=6.7.1=py310h3406613_0
  - mumps-include=5.8.1=hbdd521f_0
  - mumps-mpi=5.8.1=h098cbfa_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - netcdf4=1.7.4=nompi_py310hd27e1a9_102
  - nlohmann_json=3.12.0=h54a6638_1
  - numpy=2.2.6=py310hefbff90_0
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openmpi=5.0.8=h2fe1745_110
  - openssl=3.6.1=h35e630c_1
  - packaging=26.0=pyhcf101f3_0
  - parmetis=4.0.3=h3a7d728_1009
  - pcre2=10.47=haa7fec5_0
  - petsc=3.23.5=real_hbfed4ee_2
  - petsc4py=3.23.4=np2py310h3e2f9dd_0
  - pillow=12.1.1=py310h5a73078_0
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pkg-config=0.29.2=h4bc722e_1009
  - pkgconfig=1.5.5=pyhd8ed1ab_5
  - platformdirs=4.9.2=pyhcf101f3_0
  - pooch=1.9.0=pyhd8ed1ab_0
  - proj=9.7.1=he0df7b0_3
  - propcache=0.3.1=py310h89163eb_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.15=h3f63f65_0
  - pybind11=3.0.0=pyh9380348_1
  - pybind11-global=3.0.0=pyhf748d72_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyside6=6.10.2=py310h2007e60_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.18=hd6af730_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pyvista=0.47.1=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - qt6-main=6.10.2=hb82b983_4
  - rdma-core=61.0=h192683f_0
  - readline=8.3=h853b02a_0
  - requests=2.32.5=pyhcf101f3_1
  - rich=14.3.3=pyhcf101f3_0
  - rich-rst=1.3.2=pyhd8ed1ab_0
  - scalapack=2.2.0=h606478a_6
  - scipy=1.15.2=py310h1d65ade_0
  - scooby=0.11.0=pyhd8ed1ab_0
  - six=1.17.0=pyhe01879c_1
  - slepc=3.23.2=real_h5d6ed6e_1
  - slepc4py=3.23.2=np2py310hecb6b35_1
  - snappy=1.2.2=h03e3b7b_1
  - spirv-tools=2025.5=hb700be7_0
  - sqlite=3.51.2=h04a0ce9_0
  - suitesparse=7.10.1=ha0f6916_7100102
  - superlu=7.0.1=h8f6e6c4_0
  - superlu_dist=9.1.0=h3349319_0
  - sympy=1.14.0=pyh2585a3b_105
  - sysroot_linux-64=2.39=hc4b9eeb_5
  - tbb=2022.3.0=h8d10470_1
  - tk=8.6.13=noxft_h366c992_103
  - tomli=2.4.0=pyhcf101f3_0
  - tornado=6.5.4=py310ha78b2d2_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - ucc=1.6.0=hb729f83_1
  - ucx=1.19.1=h567e125_0
  - unicodedata2=17.0.1=py310h7c4b9e2_0
  - urllib3=2.6.3=pyhd8ed1ab_0
  - utfcpp=4.09=ha770c72_0
  - viskores=1.1.0=hca82ae8_0
  - vtk-base=9.5.2=py310h3c48d7e_7
  - wayland=1.24.0=hd6090a7_1
  - wslink=2.5.0=pyhd8ed1ab_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.13=he1eb515_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.7=hb03c661_0
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.7=hb03c661_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.5=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.7=hb03c661_0
  - yaml=0.2.5=h280c20c_3
  - yarl=1.22.0=py310h3406613_0
  - zfp=1.0.1=h909a3a2_5
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.3=hceb46e0_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - fenics-basix==0.9.0
      - gmsh==4.14.0
      - jax==0.6.2
      - jax-fem==0.0.11
      - jaxlib==0.6.2
      - ml-dtypes==0.5.4
      - opt-einsum==3.4.0
      - pyfiglet==1.0.3
      - setuptools==80.9.0
      - wheel==0.45.1

